name: Build Windows EXE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # allows manual trigger

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pyinstaller matplotlib numpy

    - name: Build EXE
      run: |
        pyinstaller --onefile tools/spore_marking_tool.py

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v4
      with:
        name: spore-marking-tool-windows
        path: dist/spore_marking_tool.exe
